### ISSUE TITLE
Private Merge: Identify history "tracks" for files/directories

### ISSUE THREAD

**Issue by matheus23** [wnfs-wg/spec#34]
# The Problem

When two private file systems get merged, you end up with multiple nodes at each revision, for example:
1. Bob writes a version of "file.txt": "Hello "
2. Alice writes two versions of "file.txt" on top of that: + "Alice", then + "!"
3. Bob writes two versions of "file.txt" concurrently on top of (1): + "Bob", then + "!"

After merging, you end up with the revisions looking like this:
| Revision | Content |
|-:|-|
| 1 | "Hello " |
| 2 | "Hello Alice", "Hello Bob" |
| 3 | "Hello Bob!", "Hello Alice!" |

Notice that the order may get "mixed up", because the order is determined by something independent of the contents (the ciphertext's hash).

When looking at the "Hello Bob!" file.txt version of revision 3, it's not clear what *that* particular version's predecessor is. We only know its previous version is included in the set of "Hello Alice" and "Hello Bob".
Being able to recover the history DAG of a file/directory should be possible from the data model for as far as you have access to read.

# Possible Solution(s)

We introduce a previous pointer array similar to what exists in the public file system. This previous pointer should identify which previous ciphertext was the previous version.
If the previous pointer is the CID of the previous ciphertext this forces the causal dependency to be possible (you can't "guess" the hash of something that you don't know about).
However, this leaks metadata: Even though a client can't *read* the previous version, they can see which of the ciphertexts was the previous one.
We *could* decide that that's very little metadata and we shouldn't worry about that, but could also do a little better by encrypting the previous pointer with the *previous* revision's node (ratchet) key.
That way, only clients that can decrypt the previous revision can read the backpointers for the future revision.
A writer can obviously encrypt these backpointers because they should have access to read revision N in order to write revision N+1.
The size of the encrypted backpointers array will likely still be leaked, but I think that's not worth compromising efficiency for. The "danger" here is that someone who can *read the current revision* knows *how many previous versions* this file was based on. I.e. they know the "N" in the n-ary merge, they know that this file was just created (no backpointers) or the file had a single previous version.

**Comment by matheus23** [comment]
@expede I think the "Possible Solution" section above pretty much explains my current thinking on how encrypted backpointers are supposed to work.

The only thing I'd add is that I'd likely put it into the encoding here:
```ts
type PrivateNode = {
  type: "wnfs/priv/dir" | "wnfs/priv/file"
  version: "0.2.0"
  // encrypted using deriveKey(ratchet)
  header: Encrypted<CBOR<PrivateNodeHeader>>
  // encrypted using deriveKey(previous) where inc(previous) = ratchet
  previous: Encrypted<CBOR<Array<CID>>>
  // ...
}
```

Another option would be to put it inside the `header`, but that'd feel a little excessive. You'd have three encryption envelopes around each other.

**Comment by expede** [comment]
@matheus23 I believe this matches the conversation we had about it a few weeks ago — I think this is good, but just to make sure that we're on the same page:

* `previous` is the only new field in the above proposal, yes?
* It's encrypted with the previous skip ratchet key?

> Another option would be to put it inside the header, but that'd feel a little excessive. You'd have three encryption envelopes around each other.

* Which header is `header`? Is that the userland or kernel?
* If kernel, I assume you mean in what I call the temporal header in my PR?

**Comment by matheus23** [comment]
> `previous` is the only new field in the above proposal, yes?

Yep.

> It's encrypted with the previous skip ratchet key?

Yep.

> Which header is `header`? Is that the userland or kernel?

kernel.

> If kernel, I assume you mean in what I call the temporal header in my PR?

No. The private header. But again, that's what I *wouldn't* recommend.
