### ISSUE TITLE
Replace nested encryption with separately encrypted headers

### ISSUE THREAD

**Issue by matheus23** [wnfs-wg/spec#47]
In WNFS today, we have a fairly fine-grained read permissioning system enabled though sharing various "levels" of keys.
Sometimes the permissioning is so granular that small ciphertexts are encrypted within other ciphertexts.
This means to read such a small ciphertext one needs to first decrypt the "box" around it. Performance can be improved by pulling out the encryption.

This means we need to figure out addressing each of the pieces though. We don't want each of the ciphertexts to have their own name(filter/accumulator), as these are expensive to calculate.
We also don't want to tag these ciphertext in a way that can be distinguished from private file shards in order to hide metadata.

**Comment by walkah** [comment]
Being handled in #58

**Comment by walkah** [comment]
Follow up PR https://github.com/wnfs-wg/spec/pull/59

**Comment by matheus23** [comment]
Closed via #58 and #59
