### ISSUE TITLE
Private Partition: Structure keys such that you can share individual version snapshots for directories

### ISSUE THREAD

**Issue by matheus23** [wnfs-wg/spec#6]
Current state: When you share access to a private directory, you'll have the ratchet and be able to read all future versions, too.

Goal: You can either share "snapshot access" to a private directory, making it possible to only read everything the current directory contains & snapshots of all entries, or you can share "forward access" by providing the whole ratchet, so the recipient can read the current version and all future ones.

**Comment by matheus23** [comment]
There's a problem with this approach: We duplicate the "userland", i.e. the pointers into child nodes: Once for the temporal structure and a second time in the snapshot structure.

I'd propose just concatenating the two types of nodes and putting them into the same block. If we do that, we can remove the redundancy of the child links. So the encoding would be something like:

```js
cbor([
  encrypt(derive_key(ratchet), cbor({
    bare_namefilter,
    ratchet, // revision
  })),
  encrypt(hash(derive_key(ratchet)), cbor({
    metadata,
    inumber,
    userland: {
      // e.g.
      "Photos": {
        snapshot_key: photos_key,
        revision_key: encrypt(derive_key(ratchet), photos_revision_key),
        link: namefilter
      }
    }))
])
```

There's some wiggle room in terms of design: we could also nest the encryption, so instead of putting two encrypted blocks side-by-side, we could put one block inside of the other:

```js
encrypt(hash(derive_key(ratchet)), cbor({
  metadata,
  inumber,
  userland: {
    // same as before
  },
  revision: encrypt(derive_key(ratchet), cbor({
    bare_namefilter,
    ratchet
  }))
}))
```

I'm not sure what's better. There's minimal parallelism you gain from the first version (you can decrypt two ciphertexts in parallel), but at the same time, separating them means you leak info about which part you're modifying, if you change one of them. That may help cross-reference files?
It seems safer to nest the encryption blocks for sure. I'm pretty sure this gets rid of the danger that co-locating these two ciphertexts brings.

There's definitely also the question of how much really brings us. We're not duplicating the "userland" (I don't like that name, maybe something like "directory entry table"?) anymore, but anytime we need to decrypt something there may be some inconsistency anyway (i.e. the key being incorrect), so we're getting rid of *some* of that possible inconsistency, but only a tiny bit of the overall.

**Comment by matheus23** [comment]
> > putting them into the same block
> 
> Any specific reason why literally in the same block? Won't it get duplicated in cases where there's concurrent writes? The namefilter is "merely" a pointer into a K/V store. It will already have many leafs between the expanded namefilter, concurrent writes, etc.

Hm, I'm not sure what you mean by "literally the same block". I just think they should be addressed using the same namefilter.

Thinking about your sentence "duplicated in cases where there's concurrent writes". I think I get what you're saying now. We could split the block into its header and the actual contents. I.e. something more along the lines of the first encoding in my post. :thinking: I'm liking the idea of not having to duplicate redundant information!

> Any rationale for putting the inumber here instead of in the temporal header? You shouldn't need the inumber unless you're building a new version, right?

Yep! :smile: 

https://github.com/WebNativeFileSystem/spec/blob/e1ce10af437d57ecd471dbb8cbf2c64c2c002870/private-wnfs.md?plain=1#L61-L68

**Comment by expede** [comment]
> What's the reasoning behind the term "userland"? 

@matheus23 It's the [established term for the user-accessible region of a system](https://en.wikipedia.org/wiki/User_space_and_kernel_space). I believe the term originally comes from Unix. The non-user accessible / system managed part is called "kernel" or "kernel space" (I've never "kernel-land" for some reason, always "kernel space" or just "kernel").

**Comment by matheus23** [comment]
Latest version of this: https://github.com/wnfs-wg/spec/blob/matheus23/meta-adjustments/spec/private-wnfs.md#the-decrypted-layer

**Comment by expede** [comment]
This looks great! I had reconstructed this last time, but @matheus23 graciously walked me through it again, and it all makes sense 🎉 I'm going to add more clarifying text, but looks good to me!
